[package]
name = "bytecode_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10"
log = "0.4"
num-derive = "0.4"
num-traits = "0.2"
test-log = "0.2.14"

[dev-dependencies]
